/*********************************************************************
*                     SEGGER Microcontroller GmbH                    *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 6.16         *
*        Compiled Nov 13 2020, 12:48:36                              *
*                                                                    *
*        (c) 1998 - 2020 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: change_cn.c                                           *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\emwin\emWin\c\change_cn.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_YaHei24B_cn;

/* Start of unicode area <CJK Unified Ideographs> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_0020[ 32] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_5BC6[ 96] = { /* code 5BC6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_XXXX___,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX____,__XXX___,____XXX_,
  _XXX____,__XXX___,X___XXX_,
  _XXXX__X,XX_XXX_X,XXX_XXX_,
  ___XXX_X,XX_X__XX,XX______,
  __XXX__X,XX__XXXX,X__X____,
  _XXX___X,XXXXXXXX,__XXXX__,
  __X____X,XXXXXX__,XXXXXXX_,
  ___XXXXX,XXXXX___,XXX_XXX_,
  _XXXXXXX,XXX____X,XXX__X__,
  _XXXXXXX,XXXXXXXX,XX______,
  __XX___X,XXXXXXXX,XX______,
  ________,XXXXXXXX,X_______,
  __XXXX__,__XXXX__,__XXXX__,
  __XXXX__,__XXXX__,__XXXX__,
  __XXXX__,__XXXX__,__XXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,__XXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_5F55[ 96] = { /* code 5F55 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,________,_XXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ________,________,_XXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ___XX___,__XXXX__,___X____,
  __XXXXX_,__XXXX__,__XXX___,
  ___XXXXX,_XXXXXX_,_XXXXX__,
  _____XX_,XXXXXXXX,XXXX____,
  ______XX,XXXXXXXX,XXX_____,
  ____XXXX,X_XXXXXX,XXX_____,
  __XXXXXX,__XXXX_X,XXXXX___,
  XXXXXX__,__XXXX__,_XXXXXX_,
  _XXX___X,XXXXXX__,__XXXXX_,
  __X____X,XXXXX___,____XX__,
  _______X,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_6237[ 96] = { /* code 6237 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____X___,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XXXX_,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXX__,________,___XXX__,
  ___XXX__,________,___XXX__,
  ___XXX__,________,___XXX__,
  ___XXX__,________,___XXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXX__,________,___XXX__,
  ___XXX__,________,________,
  __XXXX__,________,________,
  __XXX___,________,________,
  __XXX___,________,________,
  _XXXX___,________,________,
  _XXX____,________,________,
  __XX____,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_7528[ 96] = { /* code 7528 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXX__,___XXX__,___XXX__,
  ___XXX__,___XXX__,___XXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXX__,___XXX__,___XXX__,
  __XXXX__,___XXX__,___XXX__,
  __XXX___,___XXX__,___XXX__,
  _XXXX___,___XXX__,___XXX__,
  _XXXX___,___XXX_X,XXXXXX__,
  _XXXX___,___XXX_X,XXXXXX__,
  ___X____,___XXX__,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_767B[ 96] = { /* code 767B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_____XX_,___X____,
  __XXXXXX,XXX_XXX_,_XXXX___,
  __XXXXXX,XXX_XXXX,XXXXX___,
  __XXXXXX,XXX__XXX,XXX__X__,
  __X_____,XXX__XXX,XX__XXX_,
  _XXX___X,XX____XX,XX_XXXX_,
  __XXXXXX,X______X,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,_XXXXX__,
  XXXXX___,________,___XXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XX_XXXX,XXXXXXXX,XXXX_X__,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXX_,________,_XXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  _____XXX,X______X,XX______,
  ______XX,XX_____X,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_7801[ 96] = { /* code 7801 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XX_XXXXX,XXXXX___,
  _XXXXXXX,XX_XXXXX,XXXXX___,
  _XXXXXXX,XX_XXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,___XXXX_,__XXX___,
  ___XXX__,___XXX__,__XXX___,
  ___XXX__,___XXX__,__XXX___,
  __XXX___,___XXX__,__XXX___,
  __XXXXXX,XX_XXX__,__XXX___,
  _XXXXXXX,XX_XXX__,__XXX___,
  _XXXXXXX,XX_XXXXX,XXXXXXX_,
  _XXXX__X,XX_XXXXX,XXXXXXX_,
  _XXXX__X,XX_XXXXX,XXXXXXX_,
  _XXXX__X,XX______,___XXXX_,
  _XXXX__X,XX______,___XXX__,
  __XXX__X,XXXXXXXX,XX_XXX__,
  __XXX__X,XXXXXXXX,XX_XXX__,
  __XXXXXX,XXXXXXXX,XX_XXX__,
  __XXXXXX,XX______,___XXX__,
  __XXXXXX,XX______,___XXX__,
  __XXX__X,XX____XX,XXXXXX__,
  __XXX__X,XX____XX,XXXXXX__,
  ________,______XX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontchange_cn_CharInfo[10] = {
	 {   7,   7,  1, acGUI_Fontchange_cn_0020 } /* code 0020 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_5BC6 } /* code 5BC6 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_5F55 } /* code 5F55 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_6237 } /* code 6237 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_7528 } /* code 7528 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_767B } /* code 767B */
  ,{  24,  24,  3, acGUI_Fontchange_cn_7801 } /* code 7801 */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop7 = {
   0x7801 /* first character */
  ,0x7801 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  6] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop6 = {
   0x767B /* first character */
  ,0x767B /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  5] /* address of first character */
  ,&GUI_Fontchange_cn_Prop7 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop5 = {
   0x7528 /* first character */
  ,0x7528 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  4] /* address of first character */
  ,&GUI_Fontchange_cn_Prop6 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop4 = {
   0x6237 /* first character */
  ,0x6237 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  3] /* address of first character */
  ,&GUI_Fontchange_cn_Prop5 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop3 = {
   0x5F55 /* first character */
  ,0x5F55 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  2] /* address of first character */
  ,&GUI_Fontchange_cn_Prop4 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop2 = {
   0x5BC6 /* first character */
  ,0x5BC6 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  1] /* address of first character */
  ,&GUI_Fontchange_cn_Prop3 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  0] /* address of first character */
  ,&GUI_Fontchange_cn_Prop2 /* pointer to next GUI_FONT_PROP */
};
GUI_CONST_STORAGE GUI_FONT GUI_YaHei24B_cn = {
    GUI_FONTTYPE_PROP /* type of font    */
  ,31 /* height of font  */
  ,31 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontchange_cn_Prop1}
  ,25 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

