/*********************************************************************
*                     SEGGER Microcontroller GmbH                    *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 6.16         *
*        Compiled Nov 13 2020, 12:48:36                              *
*                                                                    *
*        (c) 1998 - 2020 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: change_cn.c                                           *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      31                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  31                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\emwin\emWin\c\change_cn.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_YaHei32B;

/* Start of unicode area <Basic Latin> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_0020[ 32] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_62E9[ 96] = { /* code 62E9 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  _XXXXXXX,___XX___,__XXXX__,
  _XXXXXXX,__XXXX__,_XXXX___,
  _XXXXXXX,___XXXXX,XXXX____,
  ___XXX__,____XXXX,XXX_____,
  ___XXX__,__XXXXXX,XXXX____,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXX__,_XXXXXX_,
  ___XXXXX,_XX___XX,X___XXX_,
  XXXXXXXX,______XX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,______XX,X_______,
  ___XXX__,______XX,X_______,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX__,______XX,X_______,
  _XXXXX__,______XX,X_______,
  _XXXX___,______XX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_7406[ 96] = { /* code 7406 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXX__XX,X___XXX_,
  ___XXX__,_XXX__XX,X___XXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXX__XX,X___XXX_,
  _XXXXXXX,_XXX__XX,X___XXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,______XX,X_______,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,_XXXXXXX,XXXXXXX_,
  __XXXXXX,______XX,X_______,
  XXXXXX__,X_____XX,X_______,
  _XXX____,XXXXXXXX,XXXXXXXX,
  _X______,XXXXXXXX,XXXXXXXX,
  ________,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_7BA1[ 96] = { /* code 7BA1 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXX_,_______X,XX______,
  ___XXXX_,______XX,XX______,
  ___XXXXX,XXXXX_XX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX_XX,_____XXX,_XXX____,
  _XXX__XX,X_XXXXXX,_XXXX___,
  __X____X,XXXXX_X_,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX____,________,____XXX_,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE unsigned char acGUI_Fontchange_cn_9009[ 96] = { /* code 9009 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,______XX,X_______,
  _XXXX___,_XX___XX,X_______,
  __XXXX__,_XXX__XX,X_______,
  ___XXXX_,_XXXXXXX,XXXXXX__,
  ___XXX__,XXXXXXXX,XXXXXX__,
  ____X___,XXXXXXXX,XXXXXX__,
  ________,XX____XX,X_______,
  ________,_X____XX,X_______,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX__,__XXX__X,XX______,
  ___XXX__,__XXX__X,XX__X___,
  ___XXX__,__XXX__X,XX__XXX_,
  ___XXX__,_XXXX__X,XX__XXX_,
  ___XXX__,XXXX___X,XXXXXXX_,
  ___XXX__,XXX____X,XXXXXX__,
  __XXXXX_,_X______,XXXXXX__,
  __XXXXXX,X_______,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX__XX,XXXXXXXX,XXXXXXX_,
  _XX_____,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

static GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontchange_cn_CharInfo[5] = {
   {   7,   7,  1, acGUI_Fontchange_cn_0020 } /* code 0020 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_62E9 } /* code 62E9 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_7406 } /* code 7406 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_7BA1 } /* code 7BA1 */
  ,{  24,  24,  3, acGUI_Fontchange_cn_9009 } /* code 9009 */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop5 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop4 = {
   0x7BA1 /* first character */
  ,0x7BA1 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  3] /* address of first character */
  ,&GUI_Fontchange_cn_Prop5 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop3 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  2] /* address of first character */
  ,&GUI_Fontchange_cn_Prop4 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop2 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  1] /* address of first character */
  ,&GUI_Fontchange_cn_Prop3 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontchange_cn_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontchange_cn_CharInfo[  0] /* address of first character */
  ,&GUI_Fontchange_cn_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_YaHei32B = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,31 /* height of font  */
  ,31 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontchange_cn_Prop1}
  ,25 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

