/*********************************************************************
*                     SEGGER Microcontroller GmbH                    *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter (Demoversion) for emWin version 6.16         *
*        Compiled Nov 13 2020, 12:48:36                              *
*                                                                    *
*        (c) 1998 - 2020 SEGGER Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: YaHei11.c                                             *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\emwin\emWin\c\change_cn.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei11;

/* Start of unicode area <Basic Latin> */
static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  _XXXX___,
  _XXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XXXXXX_,
  _X___XX_,
  _____XX_,
  ___XXX__,
  __XX____,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XXXXX__,
  ____XX__,
  __XXX___,
  __XXXX__,
  _X___XX_,
  _XXXXXX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ________,
  ____XX__,
  ___XXX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XXXXXXX_,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  _XX_____,
  _XXXX___,
  _XXXXX__,
  _X__XX__,
  _XXXXX__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __XXXX__,
  _XXX____,
  _XX_XX__,
  _XXXXXX_,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XXXXXX__,
  XX__XX__,
  XXXXXX__,
  _XX_XX__,
  ___XXX__,
  XXXXX___,
  XXXX____,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXXX_,
  _XXXXX__,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_4E0A[ 32] = { /* code 4E0A */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  XXXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_514D[ 32] = { /* code 514D */
  ________,________,
  ________,________,
  ________,________,
  ___XX___,________,
  __XXXXXX,________,
  _XX___XX,________,
  XXXXXXXX,XX______,
  _XX__X__,XX______,
  _XX__X__,XX______,
  _XXXXXXX,XX______,
  ___XX___,_XX_____,
  __XX_XX_,_XX_____,
  _X____XX,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_5355[ 32] = { /* code 5355 */
  ________,________,
  ________,________,
  ________,________,
  __XX___X,X_______,
  ___XX_XX,________,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_5468[ 32] = { /* code 5468 */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XX__X__,_X______,
  _XXXXXXX,_X______,
  _XX__X__,_X______,
  _XXXXXXX,XX______,
  _XX_____,_X______,
  _X_XXXXX,_X______,
  _X_XX__X,_X______,
  XX_XXXXX,_X______,
  _X_____X,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_5708[ 32] = { /* code 5708 */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _X_X_X_X,_X______,
  _XXXXXXX,XX______,
  _X___X__,_X______,
  _XXXXXXX,XX______,
  _X_X__XX,XX______,
  _XXX_XX_,_X______,
  _X_X___X,XX______,
  _XXXXXXX,XX______,
  _X______,_X______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_591A[ 32] = { /* code 591A */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  __XXXXXX,XX______,
  _XXX___X,X_______,
  ___XXXX_,________,
  __XXX_X_,________,
  _XX_XXXX,XX______,
  ___XX___,XX______,
  _XX_XXXX,X_______,
  ___XXXX_,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_5EA6[ 32] = { /* code 5EA6 */
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _XXXXXXX,XXX_____,
  _X__X___,X_______,
  _X_XXXXX,XXX_____,
  _X__X___,X_______,
  _X_XXXXX,XX______,
  _X__X___,X_______,
  _X___XXX,________,
  XX__XX_X,X_______,
  __XX____,_XX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_62E9[ 32] = { /* code 62E9 */
  ________,________,
  ________,________,
  ________,________,
  _XX_XXXX,XX______,
  _XX__X__,XX______,
  XXXX_XXX,X_______,
  _XX__XXX,X_______,
  _XX_XX__,XXX_____,
  XXXX__XX,________,
  _XX_XXXX,XX______,
  _XX___XX,________,
  _XXXXXXX,XXX_____,
  XXX___XX,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6570[ 32] = { /* code 6570 */
  ________,________,
  ________,________,
  ________,________,
  _X_X_X_X,X_______,
  _X_XXX_X,________,
  XXXXXXXX,XXX_____,
  _XXXX_XX,_X______,
  XX_X_XXX,_X______,
  __X__X_X,_X______,
  XXXXXX_X,XX______,
  _X__X__X,X_______,
  __XXX__X,XX______,
  XXX_XXX_,_X______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_65F6[ 32] = { /* code 65F6 */
  ________,________,
  ________,________,
  ________,________,
  ________,XX______,
  _XXXX___,XX______,
  _X_XXXXX,XXX_____,
  _X_XX___,XX______,
  _XXXXXX_,XX______,
  _X_XX_XX,XX______,
  _X_XX_XX,XX______,
  _X_XX___,XX______,
  _XXXX___,XX______,
  _X_XX_XX,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_68C0[ 32] = { /* code 68C0 */
  ________,________,
  ________,________,
  ________,________,
  _XX___XX,________,
  _XX___XX,X_______,
  XXXX_X__,XX______,
  _XX_XXXX,XXX_____,
  _XXX____,________,
  XXXXX_X_,_X______,
  XXX_XXXX,_X______,
  _XX__X_X,XX______,
  _XX_____,X_______,
  _XX_XXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6B21[ 32] = { /* code 6B21 */
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _X__XX__,________,
  _XX_XXXX,XXX_____,
  __XXX___,_X______,
  ___XX_X_,XX______,
  __X___X_,________,
  _XX__XXX,________,
  _XX__X_X,X_______,
  _X__XX__,XX______,
  _XXX____,_XX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6B65[ 32] = { /* code 6B65 */
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  __X__XXX,XX______,
  __X__XX_,________,
  XXXXXXXX,XXX_____,
  ________,________,
  __XX_XX_,_X______,
  _XX__XX_,XX______,
  _X___XXX,________,
  ___XXXX_,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6CE2[ 32] = { /* code 6CE2 */
  ________,________,
  ________,________,
  ________,________,
  _X____XX,________,
  __XXXXXX,XXX_____,
  ___XX_XX,_X______,
  XX_XX_XX,________,
  _XXXXXXX,XX______,
  ___XX_X_,XX______,
  _XXXXXX_,XX______,
  _XXXX_XX,X_______,
  _X_XXXXX,XX______,
  XXXX_X__,_XX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6D6E[ 32] = { /* code 6D6E */
  ________,________,
  ________,________,
  ________,________,
  _X______,XX______,
  _XXXXXXX,X_______,
  ____X_X_,XX______,
  XX__X_XX,X_______,
  _XX_XXXX,XX______,
  X______X,X_______,
  _XXXXXXX,XXX_____,
  _X____XX,________,
  _X____XX,________,
  XX__XXX_,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_6ED1[ 32] = { /* code 6ED1 */
  ________,________,
  ________,________,
  ________,________,
  _X__XXXX,XX______,
  _XX_X___,XX______,
  ____XXXX,XX______,
  XX__X_XX,XX______,
  _XXXXXXX,XXX_____,
  ___XX___,XXX_____,
  _XX_XXXX,XX______,
  _XX_X___,XX______,
  _X__XXXX,XX______,
  XX__X___,XX______,
  _______X,XX______,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_7259[ 32] = { /* code 7259 */
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  _______X,________,
  __X____X,________,
  _XX____X,________,
  _XXXXXXX,XXX_____,
  ____XX_X,________,
  ____X__X,________,
  ___XX__X,________,
  _XX____X,________,
  _X__XXXX,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_7279[ 32] = { /* code 7279 */
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XX_XXXX,XX______,
  XXXX___X,________,
  X_X_XXXX,XXX_____,
  X_X_____,XX______,
  __XXXXXX,XXX_____,
  XXX__X__,XX______,
  __X__X__,XX______,
  __X__X__,XX______,
  __X___XX,X_______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_7387[ 32] = { /* code 7387 */
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _X__X_XX,_X______,
  _XXXXXX_,X_______,
  __X_XXXX,X_______,
  _X_XXXXX,_X______,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_7406[ 32] = { /* code 7406 */
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  _XX_XX_X,_X______,
  _XX_XXXX,XX______,
  _XX_XX_X,_X______,
  XXXXXX_X,_X______,
  _XX_XXXX,XX______,
  _XX____X,________,
  _XX_XXXX,XX______,
  _XXX___X,________,
  XXXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_7BA1[ 32] = { /* code 7BA1 */
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XXXXXXX,XXX_____,
  _X_X_XX_,XX______,
  XXXXXXXX,XXX_____,
  XX______,_XX_____,
  _XXXXXXX,X_______,
  _XX_____,________,
  _XXXXXXX,XX______,
  _XX_____,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_8BBF[ 32] = { /* code 8BBF */
  ________,________,
  ________,________,
  ________,________,
  _X____XX,________,
  _XX___XX,________,
  __X_XXXX,XXX_____,
  _____X__,________,
  XXX__XXX,XX______,
  _XX__X__,_X______,
  _XXX_X__,_X______,
  _XX_XX__,_X______,
  _XX_XX__,_X______,
  _X_XX__X,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_9009[ 32] = { /* code 9009 */
  ________,________,
  ________,________,
  ________,________,
  _X__XXXX,________,
  _XX_X_XX,________,
  __X_XXXX,XX______,
  ___XX_XX,________,
  XXXXXXXX,XXX_____,
  _XX__X_X,________,
  _XX_XX_X,_XX_____,
  _XXXX__X,XX______,
  _XX_____,________,
  ___XXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_901F[ 32] = { /* code 901F */
  ________,________,
  ________,________,
  ________,________,
  _X____XX,________,
  _XXXXXXX,XX______,
  _X____XX,________,
  ____XXXX,XX______,
  XXX_X_XX,_X______,
  _XX_XXXX,XX______,
  _XX__XXX,X_______,
  _XXXX_XX,_XX_____,
  _XX_____,________,
  X__XXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_9501[ 32] = { /* code 9501 */
  ________,________,
  ________,________,
  ________,________,
  _XX_XX_X,_X______,
  _XXX_X_X,XX______,
  XX_____X,________,
  XXXXXXXX,XX______,
  XXX_XX__,_X______,
  XXXXXX_X,_X______,
  _XX_XX_X,_X______,
  _XXX__XX,________,
  _XX__XX_,XX______,
  _X__XX__,_XX_____,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_95EE[ 32] = { /* code 95EE */
  ________,________,
  ________,________,
  ________,________,
  __XX_XXX,XX______,
  _X_XX___,_X______,
  _X______,_X______,
  _X_XXXXX,_X______,
  _X_XX_XX,_X______,
  _X_XX_XX,_X______,
  _X_XXXXX,_X______,
  _X_XX___,_X______,
  _X______,_X______,
  _X____XX,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_95F4[ 32] = { /* code 95F4 */
  ________,________,
  ________,________,
  ________,________,
  __XX_XXX,XX______,
  _X_X____,_X______,
  _X______,_X______,
  _X_XXXXX,_X______,
  _X_X___X,_X______,
  _X_XXXXX,_X______,
  _X_X___X,_X______,
  _X_XXXXX,_X______,
  _X_X____,_X______,
  _X_____X,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_9644[ 32] = { /* code 9644 */
  ________,________,
  ________,________,
  ________,________,
  _XXX_XX_,_X______,
  _X_X_X__,_X______,
  _X_X_XXX,XXX_____,
  _XX_XX__,_X______,
  _XXXXXXX,_X______,
  _X_X_X_X,_X______,
  _X_X_X_X,_X______,
  _X_X_X__,_X______,
  _XXX_X__,_X______,
  _X___X_X,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE unsigned char acGUI_FontYaHei11_9AD8[ 32] = { /* code 9AD8 */
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  __X_____,X_______,
  __XXXXXX,X_______,
  ________,________,
  _XXXXXXX,XX______,
  _X_X___X,_X______,
  _X_XXXXX,_X______,
  _X______,_X______,
  _X_____X,XX______,
  ________,________,
  ________,________,
  ________,________};

static GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYaHei11_CharInfo[42] = {
   {   7,   7,  1, acGUI_FontYaHei11_0030 } /* code 0030 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0031 } /* code 0031 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0032 } /* code 0032 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0033 } /* code 0033 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0034 } /* code 0034 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0035 } /* code 0035 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0036 } /* code 0036 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0037 } /* code 0037 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0038 } /* code 0038 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0039 } /* code 0039 */
  ,{   3,   3,  1, acGUI_FontYaHei11_003A } /* code 003A */
  ,{   4,   4,  1, acGUI_FontYaHei11_0049 } /* code 0049 */
  ,{   7,   7,  1, acGUI_FontYaHei11_0050 } /* code 0050 */
  ,{  11,  11,  2, acGUI_FontYaHei11_4E0A } /* code 4E0A */
  ,{  11,  11,  2, acGUI_FontYaHei11_514D } /* code 514D */
  ,{  11,  11,  2, acGUI_FontYaHei11_5355 } /* code 5355 */
  ,{  11,  11,  2, acGUI_FontYaHei11_5468 } /* code 5468 */
  ,{  11,  11,  2, acGUI_FontYaHei11_5708 } /* code 5708 */
  ,{  11,  11,  2, acGUI_FontYaHei11_591A } /* code 591A */
  ,{  11,  11,  2, acGUI_FontYaHei11_5EA6 } /* code 5EA6 */
  ,{  11,  11,  2, acGUI_FontYaHei11_62E9 } /* code 62E9 */
  ,{  11,  11,  2, acGUI_FontYaHei11_6570 } /* code 6570 */
  ,{  11,  11,  2, acGUI_FontYaHei11_65F6 } /* code 65F6 */
  ,{  11,  11,  2, acGUI_FontYaHei11_68C0 } /* code 68C0 */
  ,{  11,  11,  2, acGUI_FontYaHei11_6B21 } /* code 6B21 */
  ,{  11,  11,  2, acGUI_FontYaHei11_6B65 } /* code 6B65 */
  ,{  11,  11,  2, acGUI_FontYaHei11_6CE2 } /* code 6CE2 */
  ,{  11,  11,  2, acGUI_FontYaHei11_6D6E } /* code 6D6E */
  ,{  11,  11,  2, acGUI_FontYaHei11_6ED1 } /* code 6ED1 */
  ,{  11,  11,  2, acGUI_FontYaHei11_7259 } /* code 7259 */
  ,{  11,  11,  2, acGUI_FontYaHei11_7279 } /* code 7279 */
  ,{  11,  11,  2, acGUI_FontYaHei11_7387 } /* code 7387 */
  ,{  11,  11,  2, acGUI_FontYaHei11_7406 } /* code 7406 */
  ,{  11,  11,  2, acGUI_FontYaHei11_7BA1 } /* code 7BA1 */
  ,{  11,  11,  2, acGUI_FontYaHei11_8BBF } /* code 8BBF */
  ,{  11,  11,  2, acGUI_FontYaHei11_9009 } /* code 9009 */
  ,{  11,  11,  2, acGUI_FontYaHei11_901F } /* code 901F */
  ,{  11,  11,  2, acGUI_FontYaHei11_9501 } /* code 9501 */
  ,{  11,  11,  2, acGUI_FontYaHei11_95EE } /* code 95EE */
  ,{  11,  11,  2, acGUI_FontYaHei11_95F4 } /* code 95F4 */
  ,{  11,  11,  2, acGUI_FontYaHei11_9644 } /* code 9644 */
  ,{  11,  11,  2, acGUI_FontYaHei11_9AD8 } /* code 9AD8 */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop32 = {
   0x9AD8 /* first character */
  ,0x9AD8 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 41] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop31 = {
   0x9644 /* first character */
  ,0x9644 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 40] /* address of first character */
  ,&GUI_FontYaHei11_Prop32 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop30 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 39] /* address of first character */
  ,&GUI_FontYaHei11_Prop31 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop29 = {
   0x95EE /* first character */
  ,0x95EE /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 38] /* address of first character */
  ,&GUI_FontYaHei11_Prop30 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop28 = {
   0x9501 /* first character */
  ,0x9501 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 37] /* address of first character */
  ,&GUI_FontYaHei11_Prop29 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop27 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 36] /* address of first character */
  ,&GUI_FontYaHei11_Prop28 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop26 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 35] /* address of first character */
  ,&GUI_FontYaHei11_Prop27 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop25 = {
   0x8BBF /* first character */
  ,0x8BBF /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 34] /* address of first character */
  ,&GUI_FontYaHei11_Prop26 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop24 = {
   0x7BA1 /* first character */
  ,0x7BA1 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 33] /* address of first character */
  ,&GUI_FontYaHei11_Prop25 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop23 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 32] /* address of first character */
  ,&GUI_FontYaHei11_Prop24 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop22 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 31] /* address of first character */
  ,&GUI_FontYaHei11_Prop23 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop21 = {
   0x7279 /* first character */
  ,0x7279 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 30] /* address of first character */
  ,&GUI_FontYaHei11_Prop22 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop20 = {
   0x7259 /* first character */
  ,0x7259 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 29] /* address of first character */
  ,&GUI_FontYaHei11_Prop21 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop19 = {
   0x6ED1 /* first character */
  ,0x6ED1 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 28] /* address of first character */
  ,&GUI_FontYaHei11_Prop20 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop18 = {
   0x6D6E /* first character */
  ,0x6D6E /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 27] /* address of first character */
  ,&GUI_FontYaHei11_Prop19 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop17 = {
   0x6CE2 /* first character */
  ,0x6CE2 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 26] /* address of first character */
  ,&GUI_FontYaHei11_Prop18 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop16 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 25] /* address of first character */
  ,&GUI_FontYaHei11_Prop17 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop15 = {
   0x6B21 /* first character */
  ,0x6B21 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 24] /* address of first character */
  ,&GUI_FontYaHei11_Prop16 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop14 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 23] /* address of first character */
  ,&GUI_FontYaHei11_Prop15 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop13 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 22] /* address of first character */
  ,&GUI_FontYaHei11_Prop14 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop12 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 21] /* address of first character */
  ,&GUI_FontYaHei11_Prop13 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop11 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 20] /* address of first character */
  ,&GUI_FontYaHei11_Prop12 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop10 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 19] /* address of first character */
  ,&GUI_FontYaHei11_Prop11 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop9 = {
   0x591A /* first character */
  ,0x591A /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 18] /* address of first character */
  ,&GUI_FontYaHei11_Prop10 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop8 = {
   0x5708 /* first character */
  ,0x5708 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 17] /* address of first character */
  ,&GUI_FontYaHei11_Prop9 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop7 = {
   0x5468 /* first character */
  ,0x5468 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 16] /* address of first character */
  ,&GUI_FontYaHei11_Prop8 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop6 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 15] /* address of first character */
  ,&GUI_FontYaHei11_Prop7 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop5 = {
   0x514D /* first character */
  ,0x514D /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 14] /* address of first character */
  ,&GUI_FontYaHei11_Prop6 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop4 = {
   0x4E0A /* first character */
  ,0x4E0A /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 13] /* address of first character */
  ,&GUI_FontYaHei11_Prop5 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop3 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 12] /* address of first character */
  ,&GUI_FontYaHei11_Prop4 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop2 = {
   0x0049 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_FontYaHei11_CharInfo[ 11] /* address of first character */
  ,&GUI_FontYaHei11_Prop3 /* pointer to next GUI_FONT_PROP */
};

static GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei11_Prop1 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontYaHei11_CharInfo[  0] /* address of first character */
  ,&GUI_FontYaHei11_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei11 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYaHei11_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

