/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "bsp_keyboard.h"
#include "Win_MonitorDLG.h"

/*BSP 板级配置头文件*/
#include "./Bsp/STemWIN_TOOL/bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_GRAPH_0    (GUI_ID_USER + 0x01)
#define ID_IMAGE_0    (GUI_ID_USER + 0x02)
#define ID_ICONVIEW_0    (GUI_ID_USER + 0x03)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_TEXT_1    (GUI_ID_USER + 0x05)
#define ID_ICONVIEW_1    (GUI_ID_USER + 0x06)
#define ID_TEXT_2    (GUI_ID_USER + 0x07)
#define ID_TEXT_3    (GUI_ID_USER + 0x08)
#define ID_TEXT_4    (GUI_ID_USER + 0x09)
#define ID_TEXT_5    (GUI_ID_USER + 0x0A)
#define ID_TEXT_6    (GUI_ID_USER + 0x0B)
#define ID_TEXT_7    (GUI_ID_USER + 0x0C)
#define ID_TEXT_8    (GUI_ID_USER + 0x0D)

#define ID_IMAGE_0_IMAGE_0  0x00

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Monitor_Win", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Nm_Deg_Graph", ID_GRAPH_0, 13, 48, 300, 180, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Device_Logo", ID_IMAGE_0, 15, 10, 24, 24, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "Connect_Show", ID_ICONVIEW_0, 57, 10, 24, 24, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "Task_Show_Text", ID_TEXT_0, 80, 10, 120, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Time_Show", ID_TEXT_1, 210, 10, 60, 30, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Menu_Icon", ID_ICONVIEW_1, 285, 10, 24, 24, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "Nm_Value_Text", ID_TEXT_2, 68, 51, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Deg_Value_Text", ID_TEXT_3, 70, 73, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Num_Value_Text", ID_TEXT_4, 71, 95, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "N.m_Title_Text", ID_TEXT_5, 34, 51, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Deg_Title_Text", ID_TEXT_6, 35, 74, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Num_Title_Text", ID_TEXT_7, 37, 94, 30, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Effect_Show", ID_TEXT_8, 271, 175, 30, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Nm_Deg_Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 0, 0, 0, 0);
    //
    // Initialization of 'Device_Logo'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
	  
    //
    // Initialization of 'Task_Show_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "task");
    TEXT_SetFont(hItem, GUI_FONT_13_1);
    //
    // Initialization of 'Time_Show'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13_1);
    //
    // Initialization of 'Nm_Value_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0080));
    //
    // Initialization of 'Deg_Value_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    //
    // Initialization of 'Num_Value_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0040FF00));
    //
    // Initialization of 'N.m_Title_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF0080));
    //
    // Initialization of 'Deg_Title_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8000));
    //
    // Initialization of 'Num_Title_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0040FF00));
    //
    // Initialization of 'Effect_Show'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0000FF00));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Connect_Show'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_1: // Notifications sent by 'Menu_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMonitor_Win
*/
WM_HWIN CreateMonitor_Win(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
