/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END


/*EMWIN 头文件*/
#include "DIALOG.h"
#include "Win_DispositionDLG.h"
#include "bsp_keyboard.h"
#include "Connect_WinDLG.h"

/*BSP 板级配置头文件*/
#include "./Bsp/STemWIN_TOOL/bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"

//#include "./Bsp/STemWIN_ICON/Analyse_Icon.c"

WM_HWIN layer[2];//两个界面
WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存
WM_HWIN EDIT_bottle;//
WM_HWIN EDIT_capacity;//
WM_HWIN draw,QR;
WM_HWIN hItem_bottle;//总瓶数Text控件句柄
WM_HWIN hItem_capacity;//灌装量Text控件句柄

int Compare_Flag = 0;
char User_num[10];
char Pawwword_num[10];

/*软键盘数据变量*/
char Edit_buff[10];//数字键盘显示当前输入字符串
char bottle_buff[10];//备份输入字符串
char capacity_buff[10];//备份输入字符串
char Input_Num[10];//数字键盘输入字符

/*数据对象句柄*/
GRAPH_DATA_Handle GraphdataV,GraphdataH;
GUI_POINT point;

/*图片对象句柄*/
extern GUI_CONST_STORAGE GUI_BITMAP bmAnalyse_Icon;

/*emwin显示封装函数共用参数*/
extern WM_HMEM hMem;
extern GUI_MEMDEV_Handle hBMP;
extern GUI_BITMAP ac;
extern char *_acbuffer;

/* 事件句柄 */
extern EventGroupHandle_t EventGroup_Handle;
/*********************************************************************
*
*       Defines
*
**********************************************************************

*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x09)
#define ID_GRAPH_0     (GUI_ID_USER + 0x0A)
#define ID_EDIT_0     (GUI_ID_USER + 0x0B)
#define ID_EDIT_1     (GUI_ID_USER + 0x0C)
#define ID_EDIT_2     (GUI_ID_USER + 0x0D)
#define ID_EDIT_3     (GUI_ID_USER + 0x0E)
#define ID_ICONVIEW_0     (GUI_ID_USER + 0x0F)
#define ID_ICONVIEW_1     (GUI_ID_USER + 0x10)
#define ID_ICONVIEW_2     (GUI_ID_USER + 0x11)
#define ID_ICONVIEW_3     (GUI_ID_USER + 0x12)
#define ID_ICONVIEW_4     (GUI_ID_USER + 0x14)
#define ID_ICONVIEW_5     (GUI_ID_USER + 0x15)
#define ID_TEXT_0     (GUI_ID_USER + 0x16)
#define ID_ICONVIEW_6     (GUI_ID_USER + 0x17)
#define ID_ICONVIEW_7     (GUI_ID_USER + 0x18)
#define ID_ICONVIEW_8     (GUI_ID_USER + 0x19)
#define ID_EDIT_4     (GUI_ID_USER + 0x1A)
#define ID_ICONVIEW_9     (GUI_ID_USER + 0x1B)
#define ID_EDIT_5     (GUI_ID_USER + 0x1C)
#define ID_ICONVIEW_10     (GUI_ID_USER + 0x1D)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Win_Disposition", ID_WINDOW_0, 0, 0, 320, 240, FRAMEWIN_CF_MOVEABLE, 0x0, 0 },
  { GRAPH_CreateIndirect, "Nm_Deg_Graph", ID_GRAPH_0, 15, 34, 305, 192, WM_CF_SHOW | WM_CF_CONST_OUTLINE, 0x0, 0 },
  { EDIT_CreateIndirect, "Deg_Target_Edit", ID_EDIT_0, 125, 225, 75, 18, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Nm_Max_Edit", ID_EDIT_1, 255, 55, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Nm_Target_Edit", ID_EDIT_2, 255, 115, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Nm_Min_Edit", ID_EDIT_3, 265, 180, 55, 20, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Nm_Max_Icon", ID_ICONVIEW_0, 240, 58, 20, 20, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Nm_Target_Icon", ID_ICONVIEW_1, 240, 115, 20, 20, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Deg_Target_Icon", ID_ICONVIEW_2, 105, 225, 20, 20, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "Nm_Min_Icon", ID_ICONVIEW_3, 240, 170, 24, 22, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "Menu_Icon", ID_ICONVIEW_4, 50, 8, 25, 25, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Task_Left_Icon", ID_ICONVIEW_5, 8, 7, 25, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Task_Select_Text", ID_TEXT_0, 90, 8, 110, 22, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Task_Right_Icon", ID_ICONVIEW_6, 114, 7, 25, 25, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Task_Add_Icon", ID_ICONVIEW_7, 252, 13, 25, 25, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Task_Delete_Icon", ID_ICONVIEW_8, 290, 6, 25, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Deg_Max_Edit", ID_EDIT_4, 175, 58, 55, 20, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Deg_Max_Icon", ID_ICONVIEW_9, 150, 58, 20, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 63, 56, 55, 20, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Deg_Min_Icon", ID_ICONVIEW_10, 35, 58, 20, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	
	GRAPH_SCALE_Handle hScaleV_Monitor_V,hScaleV_Monitor_H;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Deg_Target_Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Nm_Max_Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Nm_Target_Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Nm_Min_Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "123");
//		EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_RED);
		EDIT_SetFont(hItem,&GUI_Font13B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Task_Select_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Deg_Max_Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00000000));
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
		
    GRAPH_SetColor(hItem, GUI_WHITE, GRAPH_CI_BK);
    GRAPH_SetColor(hItem, GUI_BLACK, GRAPH_CI_GRID);
    GRAPH_SetBorder(hItem, 30, 10, 10, 10);//设置Graph图形左、上、右和下边框
    GRAPH_SetGridDistX(hItem, 25);
    GRAPH_SetGridDistY(hItem, 10);
    GRAPH_SetLineStyleH(hItem, GUI_LS_DOT);
    GRAPH_SetLineStyleV(hItem, GUI_LS_DOT);
    GRAPH_SetGridVis(hItem, 1);//设置网格线的可见性
        /* 创建垂直刻度对象 */
    hScaleV_Monitor_V = GRAPH_SCALE_Create(20, GUI_TA_HCENTER | GUI_TA_LEFT,
            GRAPH_SCALE_CF_VERTICAL, 25);
		GRAPH_SCALE_SetNumDecs(hScaleV_Monitor_V,3);//设置刻度条小数点位数

    GRAPH_SCALE_SetFactor(hScaleV_Monitor_V, 0.04);
        /* 创建水平刻度对象 */
    hScaleV_Monitor_H = GRAPH_SCALE_Create(170, GUI_TA_HCENTER | GUI_TA_LEFT,
            GRAPH_SCALE_CF_HORIZONTAL, 25);
		GRAPH_SCALE_SetNumDecs(hScaleV_Monitor_H,1);//设置刻度条小数点位数
		GRAPH_SCALE_SetFactor(hScaleV_Monitor_H, 0.04);
		
    GRAPH_AttachScale(hItem, hScaleV_Monitor_H);
    GRAPH_AttachScale(hItem, hScaleV_Monitor_V);
    
    GRAPH_SCALE_SetTextColor(hScaleV_Monitor_H, GUI_BLUE);
    GRAPH_SCALE_SetTextColor(hScaleV_Monitor_V, GUI_MAKE_COLOR(0x00FF0080));
		
		GraphdataV=GRAPH_DATA_XY_Create(GUI_RED, 600, 0, 0);
		GRAPH_AttachData(hItem, GraphdataV);
		GraphdataH=GRAPH_DATA_XY_Create(GUI_BLUE, 600, 0, 0);
	  GRAPH_AttachData(hItem, GraphdataH);   
		
		
//		GRAPH_SCALE_SetNumDecs(hItem,1);//设置刻度条小数点位数
//		GRAPH_AttachScale(hScaleV_Monitor_H,hItem);
//		GRAPH_SetAutoScrollbar(hItem,GUI_COORD_X,1);//打开水平滚动条
    GRAPH_SetVSizeX(hItem,300);
		GRAPH_SetVSizeY(hItem,300);
		
		
		/* 加载BMP图片数据到内存设备 */
//	  LoadBMP_UsingMEMDEV("0:/icon/Analyse_Icon.bmp");
//      ShowPNG("0:/icon/Analyse_Icon.c",240,170);

		hItem=WM_GetDialogItem(pMsg->hWin,ID_ICONVIEW_2);
	  LoadBMP_UsingMEMDEV("0:/icon/Add_Icon.dta",hItem);//Analyse_Icon.dta
//		ICONVIEW_AddBitmapItem(hItem,&ac,"");
//      ShowPNGEx("0:/icon/Add_Icon.bmp",hItem);
		
		hItem=WM_GetDialogItem(pMsg->hWin,ID_ICONVIEW_3);
		LoadBMP_UsingMEMDEV("0:/icon/Analyse_Icon.dta",hItem);//Add_Icon.dta
//		ICONVIEW_AddBitmapItem(hItem,&ac,"");
//		 ShowPNGEx("0:/icon/Analyse_Icon.bmp",hItem);

//		ICONVIEW_AddBitmapItem(hItem,&bmAnalyse_Icon,"");
//		ICONVIEW_AddStreamedBitmapItem(hItem,(const void *)hBMP,"");
//		ICONVIEW_SetTextColor(hItem,ICONVIEW_CI_SEL, GUI_WHITE);
		
		
//		/* 设置初始选择的图标，-1表示不选中任何图标 */
//	ICONVIEW_SetSel(hItem, 0);
//	/* 设置图标标题的字体 */
//	ICONVIEW_SetFont(hItem, GUI_FONT_16B_1);
//	/* 设置标题的对齐方式 */
//	ICONVIEW_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_BOTTOM);
//	/* 设置图标被选中时的背景色 */
//	ICONVIEW_SetBkColor(hItem, ICONVIEW_CI_SEL, GUI_MAKE_COLOR(0x40ul << 24 | 0xFFFFFF));
//	/* 设置图标的对齐方式 */
//	ICONVIEW_SetIconAlign(hItem, ICONVIEW_IA_HCENTER|ICONVIEW_IA_TOP);
//	/* 设置图标在X和Y方向上的间距 */
//	ICONVIEW_SetSpace(hItem, GUI_COORD_X, 70);
//	ICONVIEW_SetSpace(hItem, GUI_COORD_Y, 50);
	
	/* 将背景图片从内存设备写入LCD */
	GUI_MEMDEV_WriteOpaqueAt(hBMP, 0, 0);
	
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END                                                             
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Deg_Target_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Nm_Max_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Nm_Target_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			  long ssss=GUI_ALLOC_GetNumFreeBytes ();
			  printf("%ld\n",ssss);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				CreateConnect_Win();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Nm_Min_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			 Createnumber();
			 hItem_slave=WM_GetDialogItem(pMsg->hWin,ID_EDIT_3);
			 
			 
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
//      case WM_NOTIFICATION_VALUE_CHANGED:
//			 EDIT_SetText(hItem,Edit_buff);
//			 EDIT_SetFont(hItem,&GUI_Font13B_ASCII);
//			 EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00000000));
//       EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_0: // Notifications sent by 'Nm_Max_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_1: // Notifications sent by 'Nm_Target_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_2: // Notifications sent by 'Deg_Target_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_3: // Notifications sent by 'Nm_Min_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				xEventGroupSetBits(EventGroup_Handle,KEY1_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_4: // Notifications sent by 'Menu_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_5: // Notifications sent by 'Task_Left_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_6: // Notifications sent by 'Task_Right_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_7: // Notifications sent by 'Task_Add_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_8: // Notifications sent by 'Task_Delete_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Deg_Max_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_9: // Notifications sent by 'Deg_Max_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_10: // Notifications sent by 'Deg_Min_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		
		case WM_PAINT:
			
			break;
		
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWin_Disposition
*/
WM_HWIN CreateWin_Disposition(void);
WM_HWIN CreateWin_Disposition(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	 GUI_Exec();
	
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/