/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "bsp_keyboard.h"
#include "Win_Manage_SelectDLG.h"
#include "Win_MenuDLG.h"
#include "Win_System_SetDLG.h"

/*BSP 板级配置头文件*/
#include "./Bsp/STemWIN_TOOL/bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_Manage_Select     (GUI_ID_USER + 0x0F0)
#define ID_ICONVIEW_Menu     (GUI_ID_USER + 0x0F1)
#define ID_TEXT_Manage_Select     (GUI_ID_USER + 0x0F2)
#define ID_ICONVIEW_User_Manage     (GUI_ID_USER + 0x0F3)
#define ID_ICONVIEW_System_Manage     (GUI_ID_USER + 0x0F4)
#define ID_ICONVIEW_Log_Manage     (GUI_ID_USER + 0x0F5)
#define ID_TEXT_User_Manage     (GUI_ID_USER + 0x0F6)
#define ID_TEXT_System_Manage     (GUI_ID_USER + 0x0F7)
#define ID_TEXT_Log_Manage     (GUI_ID_USER + 0x0F8)


char Manage_Sel_UserSetting[]="\xe7\x94\xa8\xe6\x88\xb7\xe7\xae\xa1\xe7\x90\x86";//用户管理
char Manage_Sel_SystemSetting[]="\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86";//系统管理
char Manage_Sel_LogSetting[]="\xe6\x97\xa5\xe5\xbf\x97\xe7\xae\xa1\xe7\x90\x86";//日志管理
// USER START (Optionally insert additional defines)
// USER END
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
extern WM_HWIN Show_prev,Show_next;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Manage_Select_Win", ID_WINDOW_Manage_Select, 0, 0, 320, 240, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Menu_Icon", ID_ICONVIEW_Menu, 15, 10, 24, 24, 0, 0x00180018, 0 },
  { TEXT_CreateIndirect, "Manage_Select_Text", ID_TEXT_Manage_Select, 76, 8, 150, 40, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "User_Manage_Icon", ID_ICONVIEW_User_Manage, 15, 75, 75, 75, 0, 0x004B004B, 0 },
  { ICONVIEW_CreateIndirect, "System_Manage_Icon", ID_ICONVIEW_System_Manage, 120, 75, 75, 75, 0, 0x004B004B, 0 },
  { ICONVIEW_CreateIndirect, "Log_Manage_Icon", ID_ICONVIEW_Log_Manage, 225, 74, 75, 75, 0, 0x004B004B, 0 },
  { TEXT_CreateIndirect, "User_Manage_Text", ID_TEXT_User_Manage, 15, 175, 75, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "System_Manage_Text", ID_TEXT_System_Manage, 120, 175, 75, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Log_Manage_Text", ID_TEXT_Log_Manage, 225, 175, 75, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

	Show_next=pMsg->hWin;
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Manage_Select_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Manage_Select);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'User_Manage_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_User_Manage);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetText(hItem, Manage_Sel_UserSetting);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'System_Manage_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_System_Manage);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetText(hItem, Manage_Sel_SystemSetting);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Log_Manage_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Log_Manage);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetText(hItem, Manage_Sel_LogSetting);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		
		//主界面y
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Menu  );
		LoadBMP_UsingMEMDEV("0:/icon/Win_Manage_SelectDLG/Menu_Icon.dta",hItem);	
		//用户管理y
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_User_Manage );
		LoadBMP_UsingMEMDEV("0:/icon/Win_Manage_SelectDLG/User_Setting_Icon.dta",hItem);
		//系统管理y
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_System_Manage );
		LoadBMP_UsingMEMDEV("0:/icon/Win_Manage_SelectDLG/System_Setting_Icon.dta",hItem);
		//日志管理y
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Log_Manage  );
		LoadBMP_UsingMEMDEV("0:/icon/Win_Manage_SelectDLG/Log_Setting_Icon.dta",hItem);
		
		 long ssss=GUI_ALLOC_GetNumFreeBytes ();
			  printf("%ld\n",ssss);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_Menu: // Notifications sent by 'Menu_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				 
				 GUI_EndDialog(pMsg->hWin, 0);//结束登录页面
//			   WM_DeleteWindow(WM_GetClientWindow(pMsg->hWin));
//			WM_DeleteWindow(pMsg->hWin);
			Show_prev=pMsg->hWin;
			   CreateMenu_Win();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_User_Manage: // Notifications sent by 'User_Manage_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_System_Manage: // Notifications sent by 'System_Manage_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				Show_prev=pMsg->hWin;
				Show_next=CreateSystem_Set_Win();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_Log_Manage: // Notifications sent by 'Log_Manage_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateManage_Select_Win
*/
WM_HWIN CreateManage_Select_Win(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
