/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Win_DispositionDLG.h"
#include "bsp_keyboard.h"
#include "Win_LoginDLG.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"
#include "Win_DispositionDLG.h"
#include "bsp_keyboard.h"
#include "Win_LoginDLG.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 										(GUI_ID_USER + 0x08)
#define ID_ICONVIEW_Menu 								(GUI_ID_USER + 0x09)
#define ID_TEXT_Canlender 							(GUI_ID_USER + 0x0A)
#define ID_ICONVIEW_Save 								(GUI_ID_USER + 0x0B)
#define ID_ICONVIEW_Return 							(GUI_ID_USER + 0x0C)
#define ID_EDIT_Year 										(GUI_ID_USER + 0x0D)
#define ID_EDIT_Month 									(GUI_ID_USER + 0x0E)
#define ID_EDIT_Day 										(GUI_ID_USER + 0x0F)
#define ID_EDIT_Hour 										(GUI_ID_USER + 0x10)
#define ID_EDIT_Minute								  (GUI_ID_USER + 0x11)
#define ID_EDIT_Second 									(GUI_ID_USER + 0x12)
#define ID_TEXT_Year 										(GUI_ID_USER + 0x13)
#define ID_TEXT_Month 									(GUI_ID_USER + 0x14)
#define ID_TEXT_Day 										(GUI_ID_USER + 0x15)
#define ID_TEXT_Hour 										(GUI_ID_USER + 0x16)
#define ID_TEXT_Minute 									(GUI_ID_USER + 0x17)
#define ID_TEXT_Second 									(GUI_ID_USER + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
extern char System_Set_Time; 

char Year[]="\xe5\xb9\xb4";//年
char Month[]="\xe6\x9c\x88";//月
char Day[]="\xe6\x97\xa5";//日
char Hour[]="\xe6\x97\xb6";//时
char Minute[]="\xe5\x88\x86";//分
char Second[]="\xe7\xa7\x92";//秒

extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
extern struct Canlender_Value    CANLV;

extern EventGroupHandle_t EventGroup_Peripheral_Handle;
extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;
extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存

extern GUI_CONST_STORAGE GUI_BITMAP bmSave_Icon;//保存
extern GUI_CONST_STORAGE GUI_BITMAP bmMenu_Icon;//主菜单
extern GUI_CONST_STORAGE GUI_BITMAP bmReturn_Icon;//返回

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Calibrate_Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "ID_ICONVIEW_Menu", ID_ICONVIEW_Menu, 5, 8, 33, 33, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Canlender", ID_TEXT_Canlender, 87, 10, 90, 32, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "ID_ICONVIEW_Save", ID_ICONVIEW_Save, 230, 8, 33, 33, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "ID_ICONVIEW_Return", ID_ICONVIEW_Return, 282, 8, 33, 33, 0, 0x00140014, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Year", ID_EDIT_Year, 85, 70, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Month", ID_EDIT_Month, 85, 120, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Day", ID_EDIT_Day, 85, 170, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Hour", ID_EDIT_Hour, 240, 70, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Minute", ID_EDIT_Minute, 240, 120, 55, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "ID_EDIT_Second", ID_EDIT_Second, 240, 170, 55, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Year", ID_TEXT_Year, 15, 70, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Month", ID_TEXT_Month, 15, 120, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Day", ID_TEXT_Day, 15, 170, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Hour", ID_TEXT_Hour, 170, 68, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Minute", ID_TEXT_Minute, 170, 120, 66, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ID_TEXT_Second", ID_TEXT_Second, 170, 170, 66, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
   
// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
		case WM_INIT_DIALOG:
    //
		
		 //保存
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Save);
    ICONVIEW_AddBitmapItem(hItem,&bmSave_Icon,"");
		 //返回
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Return);
    ICONVIEW_AddBitmapItem(hItem,&bmReturn_Icon,"");
		//主菜单
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Menu);
    ICONVIEW_AddBitmapItem(hItem,&bmMenu_Icon,"");//
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Canlender);
	  TEXT_SetText(hItem,&System_Set_Time);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
	  if(atof(CANLV.Year)==0)
		{
			 snprintf(CANLV.Year, sizeof(CANLV.Year), "%s", "2025");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Year);
	  CANLV.Year_H=hItem;
    EDIT_SetText(hItem, CANLV.Year);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(atof(CANLV.Month)==0)
		{
			 snprintf(CANLV.Month, sizeof(CANLV.Month), "%s", "3");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Month);
    CANLV.Month_H=hItem;
    EDIT_SetText(hItem, CANLV.Month);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(atof(CANLV.Day)==0)
		{
			 snprintf(CANLV.Day, sizeof(CANLV.Day), "%s", "14");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Day);
    CANLV.Day_H=hItem;
    EDIT_SetText(hItem, CANLV.Day);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(atof(CANLV.Hour)==0)
		{
			 snprintf(CANLV.Hour, sizeof(CANLV.Hour), "%s", "10");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Hour);
    CANLV.Hour_H=hItem;
    EDIT_SetText(hItem, CANLV.Hour);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(atof(CANLV.Minute)==0)
		{
			 snprintf(CANLV.Minute, sizeof(CANLV.Minute), "%s", "10");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Minute);
    CANLV.Minute_H=hItem;
    EDIT_SetText(hItem, CANLV.Minute);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(atof(CANLV.Second)==0)
		{
			 snprintf(CANLV.Second, sizeof(CANLV.Minute), "%s", "40");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Second);
    CANLV.Second_H=hItem;
    EDIT_SetText(hItem, CANLV.Second);
	  EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Year'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Year);
		TEXT_SetText(hItem,Year);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Month'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Month);
		TEXT_SetText(hItem,Month);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Day'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Day);
		TEXT_SetText(hItem,Day);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Hour'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Hour);
		TEXT_SetText(hItem,Hour);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Minute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Minute);
		TEXT_SetText(hItem,Minute);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ID_TEXT_Second'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Second);
		TEXT_SetText(hItem,Second);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_Menu: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,MENU_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Save: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Return: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,SYSTEM_SET_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Year: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Year_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Month: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Month_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Day: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Day_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Hour: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Hour_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Minute: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Minute_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Second: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CANLV.Second_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		case WM_PAINT:
			GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(0,45,320,45);
//				GUI_SetPenSize(5);
//		xEventGroupSetBits(EventGroup_Peripheral_Handle,DATETIME_EVENT);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Year),CANLV.Year);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Month),CANLV.Month);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Day),CANLV.Day);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Hour),CANLV.Hour);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Minute),CANLV.Minute);
//		EDIT_SetText(WM_GetDialogItem(pMsg->hWin,ID_EDIT_Second),CANLV.Second);
		
//        GUI_SetPenSize(1);
//		    GUI_SetColor(GUI_BLACK);
//				GUI_SetLineStyle(GUI_LS_SOLID);
//				GUI_DrawLine(200,0,200,45);
//				
//		
//		    GUI_SetColor(GUI_BLACK);
//				GUI_SetLineStyle(GUI_LS_SOLID);
//				GUI_DrawLine(89,0,89,45);
//		GUI_SetPenSize(5);

			break;
		
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCalibrate_Window
*/
WM_HWIN CreateCanlender_Window(void);
WM_HWIN CreateCanlender_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
