/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Win_DispositionDLG.h"
#include "bsp_keyboard.h"
#include "Win_LoginDLG.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   					 (GUI_ID_USER + 0x00)
#define ID_IMAGE_Menu   				 (GUI_ID_USER + 0x01)
#define ID_TEXT_Connect_Set   	 (GUI_ID_USER + 0x02)
#define ID_IMAGE_Save    				 (GUI_ID_USER + 0x03)
#define ID_IMAGE_Return    			 (GUI_ID_USER + 0x04)
#define ID_TEXT_Internet_Set  	 (GUI_ID_USER + 0x05)
#define ID_TEXT_IP    					 (GUI_ID_USER + 0x06)
#define ID_TEXT_Gateway    			 (GUI_ID_USER + 0x07)
#define ID_TEXT_IP_Target    		 (GUI_ID_USER + 0x08)
#define ID_TEXT_Port    				 (GUI_ID_USER + 0x09)
#define ID_EDIT_IP    					 (GUI_ID_USER + 0x0A)
#define ID_EDIT_Gateway   			 (GUI_ID_USER + 0x0B)
#define ID_EDIT_IP_Target   		 (GUI_ID_USER + 0x0C)
#define ID_EDIT_Port    				 (GUI_ID_USER + 0x0D)
#define ID_TEXT_Usart    				 (GUI_ID_USER + 0x0E)
#define ID_TEXT_Baud_Rate   		 (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_BaudRate_Sel (GUI_ID_USER + 0x10)


// USER START (Optionally insert additional defines)
// USER END
char Connect_Text[]="\xe5\xa4\x96\xe9\x83\xa8\xe8\xbf\x9e\xe6\x8e\xa5\xe8\xae\xbe\xe7\xbd\xae";//外部连接设置
char Internet[]="\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe7\xbd\xae";//网络设置
char Usart[]="\xe4\xb8\xb2\xe5\x8f\xa3\xe8\xae\xbe\xe7\xbd\xae";//串口设置
char Address[]="IP\xe5\x9c\xb0\xe5\x9d\x80\xef\xbc\x9a:";//地址
char DCIM[]="\xe7\xbd\x91\xe5\x85\xb3\xef\xbc\x9a:";//网关
char Target[]="\xe7\x9b\xae\xe6\xa0\x87 IP \xe5\x9c\xb0\xe5\x9d\x80:";//目标
char Port[]="\xe7\xab\xaf\xe5\x8f\xa3\xe5\x8f\xb7\xef\xbc\x9a:";//端口号
char BandRate[]="\xe6\xb3\xa2\xe7\x89\xb9\xe7\x8e\x87:";//波特率


extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;
struct Connect_Value;

extern struct Menu_Value 			MV;
extern struct Connect_Value 	CONTV;


extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存

extern GUI_CONST_STORAGE GUI_BITMAP bmSave_Icon;//保存
extern GUI_CONST_STORAGE GUI_BITMAP bmMenu_Icon;//主菜单
extern GUI_CONST_STORAGE GUI_BITMAP bmReturn_Icon;//返回

char sprin[20];
char sprin1[50];


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Connect_Win", ID_WINDOW_0, 0, 0, 320, 240, FRAMEWIN_CF_MOVEABLE, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Menu_Image", ID_IMAGE_Menu, 5, 8, 33, 33, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "Connect_Set_Text", ID_TEXT_Connect_Set, 90, 12, 120, 30, 0, 0, 0 },
  { ICONVIEW_CreateIndirect, "Save_Image", ID_IMAGE_Save, 230, 8, 33, 33, 0, 0x00140014, 5 },
  { ICONVIEW_CreateIndirect, "Return_Image", ID_IMAGE_Return, 282, 8, 33, 33, 0, 0x00140014, 0 },
  { EDIT_CreateIndirect, "Internet_Set_Text", ID_TEXT_Internet_Set, 15, 56, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP_Text", ID_TEXT_IP, 98, 60, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Gateway_Text", ID_TEXT_Gateway, 108, 88, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP_Target_Text", ID_TEXT_IP_Target, 60, 121, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Port_Text", ID_TEXT_Port, 100, 154, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "IP_Edit", ID_EDIT_IP, 200, 54, 110, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Gateway_Edit", ID_EDIT_Gateway, 200, 86, 110, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "IP_Target_Edit", ID_EDIT_IP_Target, 200, 118, 110, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Port_Edit", ID_EDIT_Port, 200, 151, 110, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Usart_Text", ID_TEXT_Usart, 15, 197, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Baud_Rate_Text", ID_TEXT_Baud_Rate, 100, 197, 80, 30, 0, 0, 0 },
  { DROPDOWN_CreateIndirect, "BaudRate_Sel_Dropdown", ID_DROPDOWN_BaudRate_Sel, 200, 203, 110, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Menu_Image'
	
    //主菜单
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_Menu);
    ICONVIEW_AddBitmapItem(hItem,&bmMenu_Icon,"");//
    //
    // Initialization of 'Connect_Set_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Connect_Set);
	  TEXT_SetText(hItem,Connect_Text);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Save_Image'
    
    //保存
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_Save);
    ICONVIEW_AddBitmapItem(hItem,&bmSave_Icon,"");
    
    //
    // Initialization of 'Return_Image'
		
    //返回
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_Return);
    ICONVIEW_AddBitmapItem(hItem,&bmReturn_Icon,"");
    //
    // Initialization of 'Internet_Set_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Internet_Set);
		EDIT_SetText(hItem,Internet);
	  EDIT_SetFont(hItem,&GUI_Fontsong);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'IP_Text'
    //
//		snprintf(Address, sizeof(Address), "%s%s","IP",Address);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IP);
	
		TEXT_SetText(hItem,Address);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Gateway_Text'
    //
		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Gateway);
		
		TEXT_SetText(hItem,DCIM);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'IP_Target_Text'
    //
		snprintf(Target, sizeof(Target), "%s%s",Target,":");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IP_Target);
		
		TEXT_SetText(hItem,Target);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Port_Text'
    //
//		snprintf(Port, sizeof(Port), "%s",":");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Port);
		
		TEXT_SetText(hItem,Port);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'IP_Edit'
    //
		
		if(!CONTV.IP[0])
		{
			strcpy(CONTV.IP,"192.168.137.48");
		}
		else{snprintf(CONTV.IP, sizeof(CONTV.IP), "%s",CONTV.IP);}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_IP);
		CONTV.IP_H=hItem;
    EDIT_SetText(hItem, CONTV.IP);
		EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Gateway_Edit'
    //
		if(!CONTV.DCIM[0])
		{
			strcpy(CONTV.DCIM,"255.168.255.48");
		}
		else{snprintf(CONTV.DCIM, sizeof(CONTV.DCIM), "%s",CONTV.DCIM);}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Gateway);
		CONTV.DCIM_H=hItem; 
    EDIT_SetText(hItem,CONTV.DCIM);
		EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'IP_Target_Edit'
    //
		if(!CONTV.IP_Target[0])
		{
			strcpy(CONTV.IP_Target,"192.168.157.98");
		}
		else{snprintf(CONTV.IP_Target, sizeof(CONTV.IP_Target), "%s",CONTV.IP_Target);}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_IP_Target);
		CONTV.IP_Target_H=hItem;
    EDIT_SetText(hItem, CONTV.IP_Target);
		EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Port_Edit'
    //
		if(!CONTV.Port[0])
		{
			strcpy(CONTV.Port,"8080");
		}
		else{snprintf(CONTV.Port, sizeof(CONTV.Port), "%s",CONTV.Port);}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Port);
		CONTV.Port_H=hItem;
    EDIT_SetText(hItem, CONTV.Port);
		EDIT_SetFont(hItem,&GUI_Font13B_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Usart_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Usart);
		EDIT_SetText(hItem,Usart);
	  EDIT_SetFont(hItem,&GUI_Fontsong);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Baud_Rate_Text'
    //
//		snprintf(Num, sizeof(Num), "%s%s",Num,":");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Baud_Rate);
		TEXT_SetText(hItem,BandRate);
	  TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_BaudRate_Sel);
		DROPDOWN_SetUpMode(hItem,1);
		DROPDOWN_SetFont(hItem, GUI_FONT_13B_ASCII);
		DROPDOWN_AddString(hItem, "115200");
		DROPDOWN_AddString(hItem, "128000");
		DROPDOWN_AddString(hItem, "9600");
		DROPDOWN_AddString(hItem, "4800");

			/* 使能下来列表控件自动使用滚动条  */
			DROPDOWN_SetAutoScroll(hItem, 1);
			
			/* 设置下拉列表控件展开后的高度  */	
			DROPDOWN_SetListHeight(hItem, 120);
			
			/* 设置下拉列表控件上滚动条的宽度 */
			DROPDOWN_SetScrollbarWidth(hItem, 16);
			
			/* 设置下拉列表控件中各个选项之间的间距 */
			DROPDOWN_SetItemSpacing(hItem, 5);
			
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_IP: // Notifications sent by 'IP_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				
			
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
			hItem_slave=CONTV.IP_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
			
        break;
      }
      break;
    case ID_EDIT_Gateway: // Notifications sent by 'Gateway_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CONTV.DCIM_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_IP_Target: // Notifications sent by 'IP_Target_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CONTV.IP_Target_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Port: // Notifications sent by 'Port_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=CONTV.Port_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
		 case ID_IMAGE_Menu: // Notifications sent by 'ID_IMAGE_Menu'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,MENU_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
			 case ID_IMAGE_Save: // Notifications sent by 'ID_IMAGE_Save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
		 case ID_IMAGE_Return: // Notifications sent by 'ID_IMAGE_Return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,SYSTEM_SET_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_DROPDOWN_BaudRate_Sel: // Notifications sent by 'BaudRate_Sel_Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		
		case WM_PAINT:
			GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(0,45,320,45);
		
		GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(0,185,320,185);
			break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateConnect_Win
*/
WM_HWIN CreateConnect_Win(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
