/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Win_DispositionDLG.h"
#include "Win_LoginDLG.h"
#include "Dispositon_ChildDLG.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0              	(GUI_ID_USER + 0x00)
#define ID_CHECKBOX_Signal        (GUI_ID_USER + 0x01)
#define ID_CHECKBOX_Multi         (GUI_ID_USER + 0x02)
#define ID_EDIT_Step            	(GUI_ID_USER + 0x03)
#define ID_TEXT_Step           	  (GUI_ID_USER + 0x04)
#define ID_DROPDOWN_Dropdown      (GUI_ID_USER + 0x05)
#define ID_TEXT_Speed            	(GUI_ID_USER + 0x06)
#define ID_TEXT_Num            		(GUI_ID_USER + 0x07)
#define ID_ICONVIEW_Save          (GUI_ID_USER + 0x08)
#define ID_EDIT_Speed             (GUI_ID_USER + 0x09)
#define ID_EDIT_Num            		(GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
66t55555555555555*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Dispositon_Child", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Signal_Step", ID_CHECKBOX_Signal, 15, 45, 80, 20, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Multi_Step", ID_CHECKBOX_Multi, 15, 86, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Step_Num", ID_EDIT_Step, 205, 45, 100, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Step", ID_TEXT_Step, 92, 45, 80, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_Dropdown, 107, 86, 200, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Speed", ID_TEXT_Speed, 14, 125, 115, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Num", ID_TEXT_Num, 15, 175, 115, 20, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Save_Icon", ID_ICONVIEW_Save, 275, 165, 33, 33, 0, 0x00140014, 0 },
  { EDIT_CreateIndirect, "Speed_Set", ID_EDIT_Speed, 145, 125, 115, 25, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "EDIT_Num", ID_EDIT_Num, 145, 175, 115, 25, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
extern char Signal_Step;//单步
extern char Muti_Step;//多步

/* 事件句柄 */
extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
extern struct Disposition_Value DISPV;

extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存
// USER START (Optionally insert additional static code)
// USER END
char Step[]="\xe6\xad\xa5\xe6\x95\xb0";//步数
char Num_Step[]="\xe9\xa2\x84\xe8\xae\xa1\xe6\x8b\xa7\xe7\xb4\xa7\xe6\x95\xb0\xe9\x87\x8f";//预计拧紧数量
char Speed_Run[]="\xe8\xbd\xac\xe9\x80\x9f";//转速

char Add_DropStr[20];//\xe7\xac\xac%s\xe6\xad\xa5
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Signal_Step'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_Signal);
	  CHECKBOX_SetFont(hItem,&GUI_Fontsong);
    CHECKBOX_SetText(hItem,&Signal_Step );
    //
    // Initialization of 'Multi_Step'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_Multi);
		CHECKBOX_SetFont(hItem,&GUI_Fontsong);
    CHECKBOX_SetText(hItem, &Muti_Step);
    //
    // Initialization of 'Step_Num'-
    //
		if(!DISPV.Step[0])
		{
		strcpy(DISPV.Step,"10");
    }
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Step);
		DISPV.Step_H=hItem;
    EDIT_SetText(hItem, DISPV.Step);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Step'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Step);
		TEXT_SetFont(hItem,&GUI_Fontsong);
		TEXT_SetText(hItem,Step);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Speed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Speed);
		TEXT_SetFont(hItem,&GUI_Fontsong);
		TEXT_SetText(hItem,Speed_Run);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Num'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Num);
		TEXT_SetFont(hItem,&GUI_Fontsong);
		TEXT_SetText(hItem,Num_Step);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Speed_Set'
    //
		if(!DISPV.Speed[0])
		{
			strcpy(DISPV.Speed,"5000rpm");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Speed);
		DISPV.Speed_H=hItem;
    EDIT_SetText(hItem, DISPV.Speed);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
		if(!DISPV.Num[0])
		{
			strcpy(DISPV.Num,"1000");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Num);
		DISPV.Num_H=hItem;
    EDIT_SetText(hItem, DISPV.Num);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//保存
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Save);
	  ICONVIEW_AddBitmapItem(hItem,&bmSave_Icon,"");//
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_Dropdown);
//		DROPDOWN_SetUpMode(hItem,1);
		DROPDOWN_SetFont(hItem,&GUI_Fontsong);
		for(int i=1;i<=atoi(DISPV.Step);i++)
		{
			snprintf(Add_DropStr,sizeof(Add_DropStr),"%s%d%s","\xe7\xac\xac",i,"\xe6\xad\xa5");
			DROPDOWN_AddString(hItem, Add_DropStr);
		}
		
		/* 使能下来列表控件自动使用滚动条  */
		DROPDOWN_SetAutoScroll(hItem, 1);
			
		/* 设置下拉列表控件展开后的高度  */	
		DROPDOWN_SetListHeight(hItem, 120);
			
		/* 设置下拉列表控件上滚动条的宽度 */
		DROPDOWN_SetScrollbarWidth(hItem, 18);
			
		/* 设置下拉列表控件中各个选项之间的间距 */
		DROPDOWN_SetItemSpacing(hItem, 5);
//		DROPDOWN_SetFont(hItem, GUI_FONT_13B_ASCII);
		
//		DROPDOWN_AddString(hItem, "115200");
//		
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_CHECKBOX_Signal: // Notifications sent by 'Signal_Step'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_CHECKBOX_Multi: // Notifications sent by 'Multi_Step'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Step: // Notifications sent by 'Step_Num'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=DISPV.Step_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_DROPDOWN_Dropdown: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Save: // Notifications sent by 'Save_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,DISPOSITION_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Speed: // Notifications sent by 'Speed_Set'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=DISPV.Speed_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Num: // Notifications sent by 'ID_EDIT_Num'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=DISPV.Num_H;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateDispositon_Child
*/
WM_HWIN CreateDispositon_Child(void);
WM_HWIN CreateDispositon_Child(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
