/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Win_DispositionDLG.h"
#include "Win_LoginDLG.h"
#include "bsp_keyboard.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 		(GUI_ID_USER + 0x00)
#define ID_TEXT_Year 		(GUI_ID_USER + 0x01)
#define ID_TEXT_Month 	(GUI_ID_USER + 0x02)
#define ID_TEXT_Day 		(GUI_ID_USER + 0x03)
#define ID_EDIT_Year 		(GUI_ID_USER + 0x04)
#define ID_EDIT_Month 	(GUI_ID_USER + 0x05)
#define ID_EDIT_Day 		(GUI_ID_USER + 0x06)
#define ID_IMAGE_Save 	(GUI_ID_USER + 0x07)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Log_TimeSel_Win", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Year_Text", ID_TEXT_Year, 15, 63, 75, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Month_Text", ID_TEXT_Month, 15, 101, 75, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Day_Text", ID_TEXT_Day, 15, 139, 75, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Year_Edit", ID_EDIT_Year, 115, 63, 75, 25, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Month_Edit", ID_EDIT_Month, 115, 101, 75, 25, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Day_Edit", ID_EDIT_Day, 115, 139, 75, 25, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Save_Image", ID_IMAGE_Save, 235, 100, 45, 45, 0, 0x00140014, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;   
extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存

extern struct Log_Value LOGV;

extern char Year;//年
extern char Month;//月
extern char Day;//日

extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Year_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Year);
		TEXT_SetText(hItem,&Year);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Month_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Month);
		TEXT_SetText(hItem,&Month);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Day_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Day);
		TEXT_SetText(hItem,&Day);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Year_Edit'
    //
		if(!LOGV.Year[0])
		{
			strcpy(LOGV.Year,"2025");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Year);
	  LOGV.Year_H=hItem;
    EDIT_SetText(hItem, LOGV.Year);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Month_Edit'
    //
		if(!LOGV.Month[0])
		{
			strcpy(LOGV.Month,"8");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Month);
		LOGV.Month_H=hItem;
    EDIT_SetText(hItem, LOGV.Month);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Day_Edit'
    //
		if(!LOGV.Day[0])
		{
			strcpy(LOGV.Day,"8");
		}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Day);
		LOGV.Day_H=hItem;
    EDIT_SetText(hItem, LOGV.Day);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Save_Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_Save);
		LOGV.Save_OK=hItem;
		ICONVIEW_AddBitmapItem(hItem,&bmSave_Icon,"");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_Year: // Notifications sent by 'Year_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=LOGV.Year_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Month: // Notifications sent by 'Month_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=LOGV.Month_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Day: // Notifications sent by 'Day_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=LOGV.Day_H;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    
  // USER START (Optionally insert additional message handling)
  // USER END
		case ID_IMAGE_Save:
				switch(NCode){
				case WM_NOTIFICATION_RELEASED:
//						hItem_slave=LOGV.Save_OK;
					  xEventGroupSetBits(EventGroup_prev_Handle,LOG_EVENT);
						break;
				}
				break;
				
			}
			break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLog_TimeSel_Win
*/
WM_HWIN CreateLog_TimeSel_Win(void);
WM_HWIN CreateLog_TimeSel_Win(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
