/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END




/* 头文件*/
#include "Win_DispositionDLG.h"
#include "bsp_keyboard.h"
#include "Win_LoginDLG.h"
#include "YaHei11.h"
/*BSP 板级配置头文件*/
#include "bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 							   (GUI_ID_USER + 0x00)
#define ID_ICONVIEW_Menu 					   (GUI_ID_USER + 0x01)
#define ID_TEXT_LastTime_Show 			 (GUI_ID_USER + 0x02)
#define ID_ICONVIEW_Delete 				   (GUI_ID_USER + 0x03)
#define ID_ICONVIEW_Return 					 (GUI_ID_USER + 0x04)
#define ID_ICONVIEW_Search_Key 			 (GUI_ID_USER + 0x05)
#define ID_EDIT_Key 								 (GUI_ID_USER + 0x06)
#define ID_ICONVIEW_Calender				 (GUI_ID_USER + 0x07)
#define ID_TEXT_NowTime_Show 				 (GUI_ID_USER + 0x08)
#define ID_MULTIEDIT_Log_Show 			 (GUI_ID_USER + 0x09)
#define ID_SCROLLBAR_LogShow_Control (GUI_ID_USER + 0x0A)

#define ID_TEXT_LastTime			 			 (GUI_ID_USER + 0x0B)
// USER START (Optionally insert additional defines)
// USER END
extern GUI_CONST_STORAGE GUI_BITMAP bmSave_Icon;//保存
extern GUI_CONST_STORAGE GUI_BITMAP bmMenu_Icon;//主菜单
extern GUI_CONST_STORAGE GUI_BITMAP bmReturn_Icon;//返回

extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;
extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存

extern char Manage_Sel_LogSetting;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei11;

extern struct Log_Value 		LOGV;
extern struct Login_Value  	LV;

char Time_Str[20];
char Last_Time[]="\xe4\xb8\x8a\xe6\xac\xa1\xe8\xae\xbf\xe9\x97\xae\xe6\x97\xb6\xe9\x97\xb4";//上次访问时间
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Log_Win", ID_WINDOW_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Menu_Icon", ID_ICONVIEW_Menu, 5, 8, 33, 33, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "LastTime_Show_Text", ID_TEXT_LastTime_Show, 80, 0, 115, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "LastTime_Show", ID_TEXT_LastTime, 80, 20, 115, 20, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Delete_Icon", ID_ICONVIEW_Delete, 230, 8, 33, 33, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "Return_Icon", ID_ICONVIEW_Return, 282, 8, 33, 33, 0, 0x00140014, 0 },
  { ICONVIEW_CreateIndirect, "Search_Key_Icon", ID_ICONVIEW_Search_Key, 12, 50, 33, 33, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "Key_Edit", ID_EDIT_Key, 55, 45, 60, 41, 0, 0x64, 0 },
  { ICONVIEW_CreateIndirect, "Calender_Icon", ID_ICONVIEW_Calender, 190, 50, 33, 33, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "NowTime_Show_Text", ID_TEXT_NowTime_Show, 230, 45, 80, 44, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Log_Show_Multiedit", ID_MULTIEDIT_Log_Show, 0, 86, 320, 154, 0, 0x0, 0 },
  { SCROLLBAR_CreateIndirect, "LogShow_Control_Scrollbar", ID_SCROLLBAR_LogShow_Control, 298, 86, 20, 154, 8, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LastTime_Show_Text'
    //
//	  snprintf(Last_Time, sizeof(Last_Time), "%s\n%s-%s-%s",Last_Time,"2025","03","18");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LastTime_Show);
		TEXT_SetText(hItem,Last_Time);
		TEXT_SetFont(hItem,&GUI_FontYaHei11);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	
	  snprintf(Time_Str, sizeof(Time_Str), "%s-%s-%s","2025","03","18");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LastTime);
		TEXT_SetText(hItem,Time_Str);
		TEXT_SetFont(hItem,&GUI_Font13B_1);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Key_Edit'
    //
	  if(!LOGV.Key_Search[0])
		{
//			snprintf(LOGV.Key_Search, sizeof(LOGV.Key_Search), "%s",LV.User_Text);
			strcpy(LOGV.Key_Search,"\xe4\xbb\xbb\xe5\x8a\xa1 2");
		}
		else{snprintf(LOGV.Key_Search, sizeof(LOGV.Key_Search), "%s",LV.User_Text);}
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_Key);
	  LOGV.Key=hItem;
    TEXT_SetText(hItem,LOGV.Key_Search );
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'NowTime_Show_Text'
    //
		 if(!LOGV.Log_TimeSel[0])
		{
//			snprintf(LOGV.Log_TimeSel, sizeof(LOGV.Log_TimeSel), "%s");
			strcpy(LOGV.Log_TimeSel,"2025.3.18");
		}
		else{snprintf(LOGV.Log_TimeSel, sizeof(LOGV.Log_TimeSel), "%s.%s.%s",LOGV.Year,LOGV.Month,LOGV.Day);}
//		snprintf(LOGV.Log_TimeSel, sizeof(LOGV.Log_TimeSel), "%s.%s.%s",LOGV.Year,LOGV.Month,LOGV.Day);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NowTime_Show);
	  LOGV.Log_DateTime=hItem;
	  TEXT_SetText(hItem,LOGV.Log_TimeSel);
		TEXT_SetFont(hItem,&GUI_Font16B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Log_Show_Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_Log_Show);
    MULTIEDIT_SetText(hItem, "Multiedit");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Menu);
		ICONVIEW_AddBitmapItem(hItem,&bmMenu_Icon,"");//
		
	  hItem = WM_GetDialogItem(pMsg->hWin, 	ID_ICONVIEW_Delete);
		ICONVIEW_AddBitmapItem(hItem,&bmDel_Icon,"");//
		
		hItem = WM_GetDialogItem(pMsg->hWin, 	ID_ICONVIEW_Return);
		ICONVIEW_AddBitmapItem(hItem,&bmReturn_Icon,"");//
		
		hItem = WM_GetDialogItem(pMsg->hWin, 	ID_ICONVIEW_Search_Key);
		ICONVIEW_AddBitmapItem(hItem,&bmSearch_Icon,"");//
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, 	ID_ICONVIEW_Calender);
		ICONVIEW_AddBitmapItem(hItem,&bmCalender_Icon,"");//
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_Menu: // Notifications sent by 'Menu_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,MENU_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Delete: // Notifications sent by 'Delete_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Return: // Notifications sent by 'Return_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				xEventGroupSetBits(EventGroup_prev_Handle,MANAGE_SELECT_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Search_Key: // Notifications sent by 'Search_Key_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_EDIT_Key: // Notifications sent by 'Key_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				hItem_slave=LOGV.Key;
				xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_ICONVIEW_Calender: // Notifications sent by 'Calender_Icon'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				hItem_slave=LOGV.Log_DateTime;
				xEventGroupSetBits(EventGroup_next_Handle,LOG_CHILD_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_MULTIEDIT_Log_Show: // Notifications sent by 'Log_Show_Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_LogShow_Control: // Notifications sent by 'LogShow_Control_Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		case WM_PAINT:
			GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(0,45,320,45);
		
		    GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(55,45,55,86);
		    
		GUI_SetColor(GUI_BLACK);
				GUI_SetLineStyle(GUI_LS_SOLID);
				GUI_DrawLine(120.,45,120,86);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateLog_Win
*/
WM_HWIN CreateLog_Win(void);
WM_HWIN CreateLog_Win(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
