/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Menu_Child_WindowDLG.h"
#include "Win_DispositionDLG.h"
#include "Win_LoginDLG.h"
/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"  

#include <string.h>
#include <stddef.h>

extern EventGroupHandle_t EventGroup_next_Handle;
extern EventGroupHandle_t EventGroup_prev_Handle;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_Menu_Child (GUI_ID_USER + 0x0E)
#define ID_MULTIEDIT_Event (GUI_ID_USER + 0x10)
#define ID_ICONVIEW_Close (GUI_ID_USER + 0x11)
#define ID_TEXT_System_Version (GUI_ID_USER + 0x12)
#define ID_TEXT_Version_Num (GUI_ID_USER + 0x13)



char Menu_Child_System_Version[]="\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac";//系统版本
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Menu_Chlid_Window", ID_WINDOW_Menu_Child, 0, 0, 320, 240, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_Event, 0, 53, 320, 187, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_Close, 282, 10, 24, 24, 0, 0x00140014, 0 },
  { TEXT_CreateIndirect, "System_Version", ID_TEXT_System_Version, 5, 19, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "System_Version_Text", ID_TEXT_Version_Num, 122, 18, 110, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_Event);
    MULTIEDIT_SetText(hItem, "Multiedit");
    //
    // Initialization of 'System_Version'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_System_Version);
	  TEXT_SetText(hItem, Menu_Child_System_Version);
		TEXT_SetFont(hItem,&GUI_Fontsong);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'System_Version_Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Version_Num);
	  TEXT_SetText(hItem, "1.0-101-20240303");
		TEXT_SetFont(hItem,&GUI_Font13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	
	  //关闭
    hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Close);
		ICONVIEW_AddBitmapItem(hItem,&bmClose_Icon ,"");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MULTIEDIT_Event: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_ICONVIEW_Close: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				xEventGroupSetBits(EventGroup_prev_Handle,MENU_EVENT);
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMenu_Chlid_Window
*/
WM_HWIN CreateMenu_Chlid_Window(void);
WM_HWIN CreateMenu_Chlid_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
