/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.16                          *
*        Compiled Nov 13 2020, 12:50:00                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "event_groups.h"
/*EMWIN头文件*/
#include "DIALOG.h"
#include "Win_LoginDLG.h"
#include "bsp_keyboard.h"
#include "song.h"
#include "GUI.h"
#include "PROGBAR.h"
#include "bsp_code.h"
#include "bsp_tool.h"
#include "Win_DispositionDLG.h"
#include "./Bsp/STemWIN_TASK/Win_MenuDLG.h"
#include "YaHei24B.h"

/*BSP 板级配置头文件*/
#include "./Bsp/STemWIN_TOOL/bsp_tool.h"
#include <string.h>
#include <stddef.h>

/*FREERTOS 头文件*/
#include "FreeRTOS.h"
#include "event_groups.h"

WM_HWIN Show_prev,Show_next,login,number;

extern WM_HWIN hItem_slave;//上个界面被点击编辑框的句柄保存

char Login_OK[]="\xe7\x99\xbb      \xe5\xbd\x95";//登录
char Login_Name[]="\xe7\x94\xa8\xe6\x88\xb7";//用户
char Login_Password[]="\xe5\xaf\x86\xe7\xa0\x81";//密码
char QR_String[] = "李金隆";

extern SemaphoreHandle_t BinarySem_LCD_DEL_Handle;
extern EventGroupHandle_t EventGroup_Handle;
extern EventGroupHandle_t EventGroup_next_Handle;

/*数据变量*/
GUI_HMEM hQR;//二维码句柄
extern char Edit_buff[10];//数字键盘显示当前输入字符串



extern struct Login_Value LV;
extern struct Keyboard_Value KV;
extern struct Menu_Value MV;
extern int flag_login,flag_keyboard;
//extern GUI_BITMAP ac_buff[BITMAP_NUM];
extern int bmp_i;
extern WM_HWIN User_Wm;

extern GUI_CONST_STORAGE GUI_BITMAP bmAnalyse_Icon;
extern GUI_CONST_STORAGE GUI_FONT GUI_YaHei24B_cn;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_Uesr (GUI_ID_USER + 0x0C0)
#define ID_TEXT_Info (GUI_ID_USER + 0x0C2)
#define ID_TEXT_Name (GUI_ID_USER + 0x0C3)
#define ID_TEXT_Password (GUI_ID_USER + 0x0C4)
#define ID_EDIT_N (GUI_ID_USER + 0x0C5)
#define ID_EDIT_P (GUI_ID_USER + 0x0C6)
#define ID_BUTTON_OK (GUI_ID_USER + 0x0C7)
#define ID_ICONVIEW_Logo (GUI_ID_USER + 0x0C9)
#define ID_ICONVIEW_Code (GUI_ID_USER + 0xA99)
#define ID_ICONVIEW_Num (GUI_ID_USER + 0xB99)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "uesr", ID_FRAMEWIN_Uesr, 0, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Info", ID_TEXT_Info, 70, 12, 180, 21, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Name", ID_TEXT_Name, 20, 50, 110, 45, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Password", ID_TEXT_Password, 20, 100, 110, 45, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "N", ID_EDIT_N, 135, 50, 165, 45, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "P", ID_EDIT_P, 135, 100, 165, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_OK, 20, 150, 280, 48, 0, 0x0, 0 },
  { ICONVIEW_CreateIndirect, "Logo", ID_ICONVIEW_Logo, 10, 0, 60, 45, 0, 0x00200020, 0 },
	{ ICONVIEW_CreateIndirect, "Code", ID_ICONVIEW_Code, 265, 0, 50, 45, 0, 0x0020002C, 0 },
	{ ICONVIEW_CreateIndirect, "Code", ID_ICONVIEW_Num, 15, 200, 288, 55, 0, 0x0030003A, 0 },//0x00D50036
  // USER START (Optionally insert additional widgets)
  // USER END
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogLogin(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hDlg;
  int     NCode;
  int     Id;
	
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Info'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Info);
	  TEXT_SetFont(hItem,GUI_FONT_24B_1);
    TEXT_SetText(hItem, "LIPI-ESDR-NP-01");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Name'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Name);
	  WM_DisableWindow(hItem);
	  EDIT_SetFont(hItem,&GUI_YaHei24B_cn);
    EDIT_SetText(hItem, Login_Name);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Password'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_Password);
	  WM_DisableWindow(hItem);
	  EDIT_SetText(hItem, Login_Password);
		EDIT_SetFont(hItem,&GUI_YaHei24B_cn);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'N'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_N);
		LV.User_Wm=hItem;
		EDIT_SetFont(hItem,GUI_FONT_32B_1);
		EDIT_SetText(hItem,LV.User_Text);
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    
    //
    // Initialization of 'P'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_P);
		LV.Pwd_Wm=hItem;
		EDIT_SetFont(hItem,GUI_FONT_32B_1);
		EDIT_SetText(hItem,LV.Pwd_Text);
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		//登录按键
//		Login_OK=Text_Edit_Set(Login_OK,"    ");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
		BUTTON_SetFont(hItem,&GUI_YaHei24B_cn);
		BUTTON_SetText(hItem,Login_OK);
		BUTTON_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//设备LOGO
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Logo);
//		LoadBMP_UsingMEMDEV("0:/icon/Win_LoginDLG/Logo_Icon.dta",&LV.Logo);
//		ICONVIEW_AddBitmapItem(hItem,&LV.Logo,"");
		ICONVIEW_AddBitmapItem(hItem,&bmLogo_Icon,"");
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Code);
		ICONVIEW_AddBitmapItem(hItem,&bmDrcode ,"");
		
//			hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Num);
//		  LV.Logo=hItem;
//		  ICONVIEW_AddBitmapItem(hItem,&bmnum ,"");
			
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Num);
//		ICONVIEW_AddBitmapItem(hItem,&bmnum ,"");
		
//		hQR = GUI_QR_Create(QR_String, 2, GUI_QR_ECLEVEL_H, 0);
//		GUI_QR_Draw(hQR,260,10);	
		long sssss=GUI_ALLOC_GetNumFreeBytes ();
			printf("Init 3 Task FreeBytes %ld\n",sssss);
		
//		if(Show_prev!=LV.Login)
//		{
//			EDIT_SetFont(LV.User_Wm,&GUI_Font10S_1);
//			EDIT_SetText(LV.User_Wm,LV.User_Text);
//			EDIT_SetFont(LV.Pwd_Wm,&GUI_Font10S_1);
//			EDIT_SetText(LV.Pwd_Wm,LV.Pwd_Text);
//		}
		
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Code);
//		LoadBMP_UsingMEMDEV("0:/icon/Win_LoginDLG/Code_Icon.dta",hItem);
		
//		long ssss=GUI_ALLOC_GetNumUsedBytes ();
//			  printf("Login %ld\n",ssss);
				
		
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
		
		
		case WM_KEY:
            switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
            { 
				case GUI_KEY_ESCAPE:
                    GUI_EndDialog(hDlg, 1);
                    break;
				
                case GUI_KEY_ENTER:
                    GUI_EndDialog(hDlg, 0);
                    break;
            }
            break;
		
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_OK: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
//				Show_prev=LV.Login;
//			Show_next=CreateMenu_Win();
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
				
//			  GUI_QR_Delete(hQR);		 
//			GUI_EndDialog(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK),0);
//			Show_next=CreateMenu_Win();
//			Del_CallBack();
		xEventGroupSetBits(EventGroup_next_Handle,MENU_EVENT);
//			GUI_EndDialog(pMsg->hWin,0);
				
			
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_EDIT_N: // Notifications sent by 'Nm_Min_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				
//				 hItem_slave=WM_GetDialogItem(pMsg->hWin,ID_EDIT_N);
//			LV.User_Wm=hItem_slave;
					
			printf("切换 keyboard\n");			
//			xSemaphoreGive(BinarySem_LCD_DEL_Handle);
//			Show_next = Createnumber();	
//			
//			Show_prev=LV.Login;			
//			KV.Keyboard=Show_next;
				
			
//			 WM_DeleteWindow(Show_prev);
//			Show_prev=pMsg->hWin;
			//ICONVIEW_DeleteItem(WM_GetDialogItem(pMsg->hWin,ID_ICONVIEW_Logo),0);
			 
      // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
//				GUI_EndDialog(pMsg->hWin,0);
			
				hItem_slave=LV.User_Wm;
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);
;        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;

      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			case ID_EDIT_P: // Notifications sent by 'Nm_Min_Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
				
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
//				hItem_slave=WM_GetDialogItem(pMsg->hWin,ID_EDIT_P);
//			  LV.Pwd_Wm= hItem_slave;
				
//			flag_keyboard=1;
			flag_login=2;
//			WM_HideWindow(LV.Login);
//			WM_ShowWindow(KV.Keyboard);
			GUI_QR_Delete(hQR);
        hQR = 0;
			hItem_slave=LV.Pwd_Wm;
//			Del_CallBack();
//			WM_SetCallback(ID_EDIT_P,Edit_P_Callback);
			xEventGroupSetBits(EventGroup_next_Handle,KEYBOARD_EVENT);

//			GUI_EndDialog(LV.Login,0);
//			WM_DeleteWindow(LV.Login);
//			Del_CallBack();
//				WM_DeleteWindow(LV.Login);	
//					Show_prev=LV.Login;
//			Show_next= Createnumber();
//			KV.Keyboard=Show_next;
//			;
        // USER START (Optionally insert code for reacting on notification message)
       // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
    case ID_ICONVIEW_Logo: // Notifications sent by 'Logo'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		
		case WM_PAINT:
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Num);
		  ICONVIEW_SetFrame(hItem,GUI_COORD_X,2);
		  ICONVIEW_SetFrame(hItem,GUI_COORD_Y,2);
		  ICONVIEW_SetBkColor(hItem,ICONVIEW_CI_BK,GUI_BLACK);
		  LV.Logo=hItem;
		  ICONVIEW_AddBitmapItem(hItem,&bmnum ,"");
		
		   GUI_SetColor(GUI_BLACK);
			 GUI_SetLineStyle(GUI_LS_SOLID);
			 GUI_DrawLine(0,45,320,45);
			 GUI_SetPenSize(5);
		
		
////		 DrawCode128(20,150 , 100, 120, "EM"); // 参数：位置(x,y)、模块宽度、条码高度、文本		
			break;
		
//		 case WM_DELETE:
////			 
////				 LV.Login=0;
////				 printf("DeleteLogin\n");
////			 
////			 
////			  if(!KV.Keyboard)
////			 {
////				 KV.Keyboard=Createnumber();printf("Createnumber\n");
////			 }
////			 
////			 WM_HWIN hIcon = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_Logo);
////            ICONVIEW_DeleteItem(hIcon, 0);
////			 
//			  for (int i = 0; i < BITMAP_NUM; i++) {
//        if (ac_buff[i].pData) {
//            GUI_ALLOC_Free(*ac_buff[i].pData);
//            ac_buff[i].pData = NULL;
//        }
//    }
//    memset(ac_buff, 0, sizeof(ac_buff));
//    bmp_i = 0;
////		long mm=GUI_ALLOC_GetNumFreeBytes ();
////		  printf("Delete Login After FreeBytes %ld\n",ssss);	
////			 
////		 
//            // 释放二维码资源
//            if (hQR) {
//                GUI_QR_Delete(hQR);
//                hQR = 0;
//            }
//						
//						long mm=GUI_ALLOC_GetNumFreeBytes ();
//		  printf("Delete Login After FreeBytes %ld\n",mm);	
//						 break;
						
//						
//						
		
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}



void Del_CallBack(void)
{
	
//	GUI_EndDialog(LV.Login,0);

////				 GUI_Delay(50);
//				 KV.Keyboard=0;
//			 if(!KV.Keyboard)
//			 {
//				 	
//				 KV.Keyboard=Createnumber();printf("Createnumber\n");
//			 }
			 
//	if(LV.Login)
//	{
//		WM_DeleteWindow(LV.Login);
//		LV.Login=0;
//	}
			  
//			 	GUI_ExecCreatedDialog(KV.Keyboard);
			 
//			  for (int i = 0; i < BITMAP_NUM; i++) {
//        if (ac_buff[i].pData) {
//            GUI_ALLOC_Free(*ac_buff[i].pData);
//            ac_buff[i].pData = NULL;
//        }
//    }
//    memset(ac_buff, 0, sizeof(ac_buff));
//    bmp_i = 0;
//		
//			 
//            // 释放二维码资源
//            if (hQR) {
//                GUI_QR_Delete(hQR);
//                hQR = 0;
//            }
//						
//					GUI_EndDialog(LV.Login,0);	 
//			 	WM_DeleteWindow(LV.Login);
//		    LV.Login=0;
				printf("DeleteLogin\n");
//	 GUI_Exec();
			 
			 WM_ValidateWindow(WM_HBKWIN);
			 long mm=GUI_ALLOC_GetNumFreeBytes ();
		  printf("Delete Login After FreeBytes %ld\n",mm);	
}

void Del_CallBack1(void)
{			 
	
		 
	
	(KV.Keyboard,0);
//			 WM_DeleteWindow(KV.Keyboard);
		    KV.Keyboard=0;
	 printf("DeleteKeyboard\n");
//			  GUI_Exec();
	 
//				 GUI_Delay(50);
	
//	 for (int i = 0; i < BITMAP_NUM; i++) {
//        if (ac_buff[i].pData) {
//            GUI_ALLOC_Free(*ac_buff[i].pData);
//            ac_buff[i].pData = NULL;
//        }
//    }
//    memset(ac_buff, 0, sizeof(ac_buff));
//    bmp_i = 0;
		
	
		LV.Login=0;
		  if(!LV.Login)
			 {
				 LV.Login=CreateLogin();
				 printf("CreateLogin\n");
			 }
//			 		 	 GUI_Exec();
//			 
//				 GUI_Delay(50);
//	GUI_ExecCreatedDialog(LV.Login);
				
			
		long mm=GUI_ALLOC_GetNumFreeBytes ();
		  printf("Delete Keyboard After FreeBytes %ld\n",mm);	
		

		 
		 
		 
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************

*       Createuesr
*/
WM_HWIN CreateLogin(void) {
  WM_HWIN hWin;
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate),_cbDialogLogin, WM_HBKWIN, 0, 0);
  printf("[DEBUG] 登录窗口句柄: %p\n", hWin);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
